apiVersion: v1
kind: Service
metadata:
  name: starwars-api-service
spec:
  type: ClusterIP
  selector:
    app: starwars-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      #nodePort: 30007